brew "mergiraf"
brew "mise"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "ghostty"
cask "hiddenbar"
cask "raycast"
cask "scroll-reverser"
cask "stats"
cask "zed"
cask "orbstack"
cask "yaak"
