[tools]
python = "latest"
uv = "latest"
node = "24"
go = "latest"
golangci-lint = "latest"
terraform = "latest"
tflint = "latest"

gh = "latest"
xh = "latest"
fzf = "latest"
eza = "latest"
zoxide = "latest"
ripgrep = "latest"
delta = "latest"
bat = "latest"
"aqua:go-task/task" = "latest"

codex = "latest"

[env]
AWS_PROFILE = "MaximAdmin"
